using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ticket_to_ride.Model
{
    public class MapGenerator
    {
        List<Connection> _connections = new List<Connection>();
        List<Location> _location = new List<Location>();

        public Map CreateMap()
        {

            _location.Add(new Location { Identifier = "0", X = 68, Y = 607 });
            _location.Add(new Location { Identifier = "1", X = 162, Y = 662 });
            _location.Add(new Location { Identifier = "2", X = 94, Y = 501 });
            _location.Add(new Location { Identifier = "3", X = 202, Y = 518 });
            _location.Add(new Location { Identifier = "4", X = 274, Y = 462 });
            _location.Add(new Location { Identifier = "5", X = 269, Y = 522 });
            _location.Add(new Location { Identifier = "6", X = 281, Y = 356 });
            _location.Add(new Location { Identifier = "7", X = 163, Y = 353 });
            _location.Add(new Location { Identifier = "8", X = 278, Y = 247 });
            _location.Add(new Location { Identifier = "9", X = 165, Y = 114 });
            _location.Add(new Location { Identifier = "10", X = 365, Y = 244 });
            _location.Add(new Location { Identifier = "11", X = 346, Y = 309 });
            _location.Add(new Location { Identifier = "12", X = 413, Y = 326 });
            _location.Add(new Location { Identifier = "13", X = 455, Y = 366 });
            _location.Add(new Location { Identifier = "14", X = 368, Y = 409 });
            _location.Add(new Location { Identifier = "15", X = 463, Y = 436 });
            _location.Add(new Location { Identifier = "16", X = 500, Y = 499 });
            _location.Add(new Location { Identifier = "17", X = 363, Y = 482 });
            _location.Add(new Location { Identifier = "18", X = 619, Y = 535 });
            _location.Add(new Location { Identifier = "19", X = 560, Y = 640 });
            _location.Add(new Location { Identifier = "20", X = 784, Y = 619 });
            _location.Add(new Location { Identifier = "21", X = 841, Y = 643 });
            _location.Add(new Location { Identifier = "22", X = 920, Y = 624 });
            _location.Add(new Location { Identifier = "23", X = 827, Y = 544 });
            _location.Add(new Location { Identifier = "24", X = 726, Y = 495 });
            _location.Add(new Location { Identifier = "25", X = 661, Y = 512 });
            _location.Add(new Location { Identifier = "26", X = 622, Y = 399 });
            _location.Add(new Location { Identifier = "27", X = 549, Y = 355 });
            _location.Add(new Location { Identifier = "28", X = 560, Y = 444 });
            _location.Add(new Location { Identifier = "29", X = 221, Y = 312 });
            _location.Add(new Location { Identifier = "30", X = 460, Y = 234 });
            _location.Add(new Location { Identifier = "31", X = 510, Y = 122 });
            _location.Add(new Location { Identifier = "32", X = 575, Y = 50 });
            _location.Add(new Location { Identifier = "33", X = 840, Y = 50 });
            _location.Add(new Location { Identifier = "34", X = 734, Y = 235 });
            _location.Add(new Location { Identifier = "35", X = 922, Y = 207 });
            _location.Add(new Location { Identifier = "36", X = 919, Y = 359 });
            _location.Add(new Location { Identifier = "37", X = 916, Y = 449 });
            _location.Add(new Location { Identifier = "38", X = 915, Y = 517 });
            _location.Add(new Location { Identifier = "39", X = 679, Y = 294 });
            _connections.Add(new Connection(_location[0], _location[1], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[1], _location[0], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[1], _location[3], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[3], _location[1], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[3], _location[2], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[2], _location[3], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[2], _location[0], 1, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[0], _location[2], 1, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[3], _location[5], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[5], _location[3], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[5], _location[4], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[4], _location[5], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[4], _location[3], 3, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[3], _location[4], 3, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[4], _location[17], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[17], _location[4], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[17], _location[5], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[5], _location[17], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[4], _location[6], 4, ConnectionColour.Black));
            _connections.Add(new Connection(_location[6], _location[4], 4, ConnectionColour.Black));
            _connections.Add(new Connection(_location[4], _location[7], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[7], _location[4], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[7], _location[6], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[6], _location[7], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[7], _location[29], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[29], _location[7], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[29], _location[6], 1, ConnectionColour.White));
            _connections.Add(new Connection(_location[6], _location[29], 1, ConnectionColour.White));
            _connections.Add(new Connection(_location[29], _location[8], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[8], _location[29], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[8], _location[10], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[10], _location[8], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[10], _location[11], 1, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[11], _location[10], 1, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[11], _location[6], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[6], _location[11], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[11], _location[29], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[29], _location[11], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[9], _location[8], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[8], _location[9], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[10], _location[30], 3, ConnectionColour.White));
            _connections.Add(new Connection(_location[30], _location[10], 3, ConnectionColour.White));
            _connections.Add(new Connection(_location[30], _location[12], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[12], _location[30], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[10], _location[12], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[12], _location[10], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[12], _location[11], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[11], _location[12], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[6], _location[12], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[12], _location[6], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[12], _location[13], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[13], _location[12], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[6], _location[14], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[14], _location[6], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[6], _location[17], 4, ConnectionColour.Black));
            _connections.Add(new Connection(_location[17], _location[6], 4, ConnectionColour.Black));
            _connections.Add(new Connection(_location[30], _location[31], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[31], _location[30], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[31], _location[32], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[32], _location[31], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[32], _location[33], 8, ConnectionColour.Red));
            _connections.Add(new Connection(_location[33], _location[32], 8, ConnectionColour.Red));
            _connections.Add(new Connection(_location[33], _location[35], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[35], _location[33], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[35], _location[36], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[36], _location[35], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[36], _location[37], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[37], _location[36], 4, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[37], _location[38], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[38], _location[37], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[38], _location[23], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[23], _location[38], 4, ConnectionColour.White));
            _location.Add(new Location { Identifier = "40", X = 922, Y = 572 });
            _connections.Add(new Connection(_location[38], _location[40], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[40], _location[38], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[40], _location[22], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[22], _location[40], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[22], _location[21], 3, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[21], _location[22], 3, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[21], _location[20], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[20], _location[21], 2, ConnectionColour.Undefined));
            _location.Add(new Location { Identifier = "41", X = 730, Y = 644 });
            _connections.Add(new Connection(_location[20], _location[41], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[41], _location[20], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[41], _location[21], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[21], _location[41], 3, ConnectionColour.Red));
            _location.Add(new Location { Identifier = "42", X = 702, Y = 591 });
            _connections.Add(new Connection(_location[41], _location[42], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[42], _location[41], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[17], _location[14], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[14], _location[17], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[14], _location[13], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[13], _location[14], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[13], _location[15], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[15], _location[13], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[15], _location[14], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[14], _location[15], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[15], _location[16], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[16], _location[15], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[16], _location[17], 4, ConnectionColour.Black));
            _connections.Add(new Connection(_location[17], _location[16], 4, ConnectionColour.Black));
            _connections.Add(new Connection(_location[16], _location[18], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[18], _location[16], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[18], _location[19], 3, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[19], _location[18], 3, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[19], _location[16], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[16], _location[19], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[15], _location[28], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[28], _location[15], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[13], _location[27], 3, ConnectionColour.White));
            _connections.Add(new Connection(_location[27], _location[13], 3, ConnectionColour.White));
            _connections.Add(new Connection(_location[27], _location[28], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[28], _location[27], 2, ConnectionColour.White));
            _connections.Add(new Connection(_location[28], _location[26], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[26], _location[28], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[26], _location[27], 1, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[27], _location[26], 1, ConnectionColour.Undefined));
            _location.Add(new Location { Identifier = "43", X = 538, Y = 272 });
            _location.Add(new Location { Identifier = "44", X = 635, Y = 178 });
            _location.Add(new Location { Identifier = "45", X = 737, Y = 121 });
            _location.Add(new Location { Identifier = "46", X = 828, Y = 213 });
            _location.Add(new Location { Identifier = "47", X = 787, Y = 322 });
            _connections.Add(new Connection(_location[33], _location[46], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[46], _location[33], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[46], _location[45], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[45], _location[46], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[44], _location[34], 4, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[34], _location[44], 4, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[44], _location[43], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[43], _location[44], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[45], _location[44], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[44], _location[45], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[34], _location[45], 4, ConnectionColour.Red));
            _connections.Add(new Connection(_location[45], _location[34], 4, ConnectionColour.Red));
            _connections.Add(new Connection(_location[45], _location[33], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[33], _location[45], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[46], _location[35], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[35], _location[46], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[46], _location[47], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[47], _location[46], 3, ConnectionColour.Red));
            _connections.Add(new Connection(_location[34], _location[47], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[47], _location[34], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[34], _location[39], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[39], _location[34], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[39], _location[43], 4, ConnectionColour.Red));
            _connections.Add(new Connection(_location[43], _location[39], 4, ConnectionColour.Red));
            _connections.Add(new Connection(_location[43], _location[30], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[30], _location[43], 2, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[43], _location[12], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[12], _location[43], 3, ConnectionColour.Black));
            _connections.Add(new Connection(_location[43], _location[27], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[27], _location[43], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[27], _location[39], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[39], _location[27], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[26], _location[24], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[24], _location[26], 4, ConnectionColour.Orange));
            _connections.Add(new Connection(_location[24], _location[25], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[25], _location[24], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[25], _location[28], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[28], _location[25], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[42], _location[24], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[24], _location[42], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[42], _location[25], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[25], _location[42], 3, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[19], _location[41], 6, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[41], _location[19], 6, ConnectionColour.Pink));
            _location.Add(new Location { Identifier = "48", X = 788, Y = 422 });
            _location.Add(new Location { Identifier = "49", X = 850, Y = 432 });
            _location.Add(new Location { Identifier = "50", X = 845, Y = 350 });
            _connections.Add(new Connection(_location[49], _location[37], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[37], _location[49], 2, ConnectionColour.Pink));
            _connections.Add(new Connection(_location[49], _location[23], 4, ConnectionColour.Red));
            _connections.Add(new Connection(_location[23], _location[49], 4, ConnectionColour.Red));
            _connections.Add(new Connection(_location[23], _location[48], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[48], _location[23], 3, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[48], _location[24], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[24], _location[48], 2, ConnectionColour.Red));
            _connections.Add(new Connection(_location[48], _location[26], 4, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[26], _location[48], 4, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[26], _location[47], 6, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[47], _location[26], 6, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[39], _location[47], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[47], _location[39], 4, ConnectionColour.White));
            _connections.Add(new Connection(_location[47], _location[50], 1, ConnectionColour.Red));
            _connections.Add(new Connection(_location[50], _location[47], 1, ConnectionColour.Red));
            _connections.Add(new Connection(_location[50], _location[36], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[36], _location[50], 2, ConnectionColour.Black));
            _connections.Add(new Connection(_location[48], _location[49], 2, ConnectionColour.Undefined));
            _connections.Add(new Connection(_location[49], _location[48], 2, ConnectionColour.Undefined));





            //_location.Add(new Location { Identifier = "0", X = 245, Y = 656 });
            //_location.Add(new Location { Identifier = "1", X = 236, Y = 555 });
            //_location.Add(new Location { Identifier = "2", X = 362, Y = 641 });
            //_location.Add(new Location { Identifier = "3", X = 360, Y = 539 });
            //_location.Add(new Location { Identifier = "4", X = 365, Y = 428 });
            //_location.Add(new Location { Identifier = "5", X = 415, Y = 382 });
            //_location.Add(new Location { Identifier = "6", X = 451, Y = 330 });
            //_location.Add(new Location { Identifier = "7", X = 347, Y = 357 });
            //_location.Add(new Location { Identifier = "8", X = 290, Y = 245 });
            //_location.Add(new Location { Identifier = "9", X = 424, Y = 520 });
            //_location.Add(new Location { Identifier = "10", X = 513, Y = 499 });
            //_location.Add(new Location { Identifier = "11", X = 460, Y = 431 });
            //_location.Add(new Location { Identifier = "12", X = 517, Y = 325 });
            //_location.Add(new Location { Identifier = "13", X = 515, Y = 260 });
            //_location.Add(new Location { Identifier = "14", X = 509, Y = 178 });
            //_location.Add(new Location { Identifier = "15", X = 588, Y = 174 });
            //_location.Add(new Location { Identifier = "16", X = 518, Y = 399 });
            //_location.Add(new Location { Identifier = "17", X = 599, Y = 405 });
            //_location.Add(new Location { Identifier = "18", X = 624, Y = 588 });
            //_location.Add(new Location { Identifier = "19", X = 591, Y = 456 });
            //_location.Add(new Location { Identifier = "20", X = 593, Y = 325 });
            //_location.Add(new Location { Identifier = "21", X = 706, Y = 594 });
            //_location.Add(new Location { Identifier = "22", X = 678, Y = 452 });
            //_location.Add(new Location { Identifier = "23", X = 703, Y = 526 });
            //_location.Add(new Location { Identifier = "24", X = 659, Y = 320 });
            //_location.Add(new Location { Identifier = "25", X = 670, Y = 63 });
            //_location.Add(new Location { Identifier = "26", X = 756, Y = 50 });
            //_location.Add(new Location { Identifier = "27", X = 786, Y = 290 });
            //_location.Add(new Location { Identifier = "28", X = 786, Y = 449 });
            //_location.Add(new Location { Identifier = "29", X = 969, Y = 447 });
            //_location.Add(new Location { Identifier = "30", X = 864, Y = 359 });
            //_location.Add(new Location { Identifier = "31", X = 788, Y = 558 });
            //_connections.Add(new Connection(_location[1], _location[3], 2, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[3], _location[1], 2, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[3], _location[2], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[2], _location[3], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[2], _location[0], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[0], _location[2], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[0], _location[1], 2, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[1], _location[0], 2, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[9], _location[4], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[4], _location[9], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[4], _location[11], 2, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[11], _location[4], 2, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[11], _location[10], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[10], _location[11], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[14], _location[15], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[15], _location[14], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[24], _location[27], 2, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[27], _location[24], 2, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[12], _location[20], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[20], _location[12], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[19], _location[10], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[10], _location[19], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[3], _location[9], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[9], _location[3], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[9], _location[10], 1, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[10], _location[9], 1, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[11], _location[5], 1, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[5], _location[11], 1, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[5], _location[6], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[6], _location[5], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[6], _location[12], 1, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[12], _location[6], 1, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[12], _location[16], 1, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[16], _location[12], 1, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[16], _location[11], 1, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[11], _location[16], 1, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[16], _location[5], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[5], _location[16], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[22], _location[23], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[23], _location[22], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[21], _location[31], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[31], _location[21], 2, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[31], _location[28], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[28], _location[31], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[22], _location[28], 3, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[28], _location[22], 3, ConnectionColour.Red));
            //_connections.Add(new Connection(_location[22], _location[24], 3, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[24], _location[22], 3, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[25], _location[26], 3, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[26], _location[25], 3, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[5], _location[7], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[7], _location[5], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[7], _location[8], 3, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[8], _location[7], 3, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[20], _location[17], 1, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[17], _location[20], 1, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[20], _location[24], 1, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[24], _location[20], 1, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[17], _location[19], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[19], _location[17], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[17], _location[22], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[22], _location[17], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[17], _location[16], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[16], _location[17], 1, ConnectionColour.White));
            //_connections.Add(new Connection(_location[19], _location[18], 3, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[18], _location[19], 3, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[18], _location[21], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[21], _location[18], 2, ConnectionColour.White));
            //_connections.Add(new Connection(_location[19], _location[23], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[23], _location[19], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[26], _location[27], 6, ConnectionColour.Black));
            //_connections.Add(new Connection(_location[27], _location[26], 6, ConnectionColour.Black));
            //_connections.Add(new Connection(_location[27], _location[30], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[30], _location[27], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[30], _location[29], 3, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[29], _location[30], 3, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[29], _location[28], 6, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[28], _location[29], 6, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[28], _location[30], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[30], _location[28], 2, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[28], _location[24], 3, ConnectionColour.Black));
            //_connections.Add(new Connection(_location[24], _location[28], 3, ConnectionColour.Black));
            //_connections.Add(new Connection(_location[12], _location[13], 1, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[13], _location[12], 1, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[13], _location[14], 2, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[14], _location[13], 2, ConnectionColour.Orange));
            //_connections.Add(new Connection(_location[15], _location[25], 3, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[25], _location[15], 3, ConnectionColour.Pink));
            //_connections.Add(new Connection(_location[15], _location[24], 5, ConnectionColour.Undefined));
            //_connections.Add(new Connection(_location[24], _location[15], 5, ConnectionColour.Undefined));






            return new Map(_connections, _location);
        }

    }
}
